### ISSUE TITLE
将startup事件识别为client事件而无法加载（可能是ProbeJS问题）

### ISSUE THREAD

**Issue by Eternal-Snowstorm** [gizmo-ds/taczjs-mod#1]
TaCZJSEvents.onGunIndexLoad这一事件在client和startup里面都有，在statup里写上时在加载过程中会被报错，显示为这一事件只在client中有效
![image](https://github.com/user-attachments/assets/bf314086-48f7-47ba-9465-89c84eeefb4b)

**Comment by gizmo-ds** [comment]
client 的事件改名为 TaCZJSEvents.onClientGunIndexLoad 了, 更新后再尝试下

https://github.com/gizmo-ds/taczjs-mod/releases/tag/v1.1.1%2Bmc1.20.1

**Comment by Eternal-Snowstorm** [comment]
> client 的事件改名为 TaCZJSEvents.onClientGunIndexLoad 了, 更新后再尝试下
> 
> https://github.com/gizmo-ds/taczjs-mod/releases/tag/v1.1.1%2Bmc1.20.1

感谢作者大大，问题已解决
