### ISSUE TITLE
枪械删除导致车万女仆mod触发崩服错误

### ISSUE THREAD

**Issue by Eternal-Snowstorm** [gizmo-ds/taczjs-mod#2]
本人整合包同时删除了枪械、子弹与配件，修改了子弹、枪械、配件配方与修改了扳手的client动作。在操作后使用整合包内的车万女仆时发生了错误：切换女仆模式时发生错误使本地服务器崩溃。
![报错](https://github.com/user-attachments/assets/0312b8bd-185e-4901-826c-24cc2fcb4e33)
[crash-2024-11-10_21.37.54-client.txt](https://github.com/user-attachments/files/17691682/crash-2024-11-10_21.37.54-client.txt)

在删除startup_script里面进行TaCZ JS修改的文件夹后重启发现可以正常切换女仆模式
![删除1](https://github.com/user-attachments/assets/51ceddd3-566b-4246-abb1-700f84ee8c87)

重新加上Tacz JS修改的文件夹后进行排查，发现是删除枪械导致。
![删除2](https://github.com/user-attachments/assets/45b04c1a-d988-4ad7-aa93-dd275861efac)

**Comment by gizmo-ds** [comment]
这似乎是 [Touhou Little Maid](https://github.com/TartaricAcid/TouhouLittleMaid) 的问题 [TaskGunAttack.java#L41](https://github.com/TartaricAcid/TouhouLittleMaid/blob/00169415c57e8dcb829e6884651d3c8a77acaecb/src/main/java/com/github/tartaricacid/touhoulittlemaid/compat/tacz/task/TaskGunAttack.java#L41) https://github.com/TartaricAcid/TouhouLittleMaid/issues/590  
你可以尝试不移除 `tacz:glock_17` 的 Index 而是仅移除该枪械的制作配方

**Comment by VechniMetel** [comment]
已确认为车万女仆问题，只能等943修了

**Comment by Eternal-Snowstorm** [comment]
已确认为车万女仆问题，只能等943修了

**Comment by TartaricAcid** [comment]
![image](https://github.com/user-attachments/assets/9bf5a3ac-46af-4ada-b911-5f168cca717b)
解决了，现在把格洛克删掉，图标会被替换成这个
