### ISSUE TITLE
The mod might need to rewriting most of the code later in the future.....

### ISSUE THREAD

**Issue by Hidocmatn** [gizmo-ds/taczjs-mod#3]
Dear gizmo-ds
I'm sorry to tell you but according to the TACZ dev team, breaking changes will be made to the resource loading part of TACZ mod in the next release, so I hope you will be prepared for these changes.
The event system won't change a lot but the current recipe system and other resource loaders will totally break down, so you might have to rewrite the code if you want to continue supporting the next version of TACZ.
Thanks for your reading.

**Comment by gizmo-ds** [comment]
Thank you for your reminder! I’m looking forward to the upcoming new version of TACZ. I will follow up and make the necessary updates after the new version is released.

**Comment by nebulazorua** [comment]
Any updates?

**Comment by gizmo-ds** [comment]
> Any updates?

I've been quite busy with work recently, but I will update it when I have some free time.
